package com.task.gh_repos_api;

import lombok.experimental.UtilityClass;

@UtilityClass
public class GithubApiStubs {
    String getRepositoriesResponseStub() {
        return """
                [
                  {
                    "id": 892178995,
                    "node_id": "R_kgDONS2SMw",
                    "name": "codeForces_tasks",
                    "full_name": "Bartoszk236/codeForces_tasks",
                    "private": false,
                    "owner": {
                      "login": "Bartoszk236",
                      "id": 148446098,
                      "node_id": "U_kgDOCNkbkg",
                      "avatar_url": "https://avatars.githubusercontent.com/u/148446098?v=4",
                      "gravatar_id": "",
                      "url": "https://api.github.com/users/Bartoszk236",
                      "html_url": "https://github.com/Bartoszk236",
                      "followers_url": "https://api.github.com/users/Bartoszk236/followers",
                      "following_url": "https://api.github.com/users/Bartoszk236/following{/other_user}",
                      "gists_url": "https://api.github.com/users/Bartoszk236/gists{/gist_id}",
                      "starred_url": "https://api.github.com/users/Bartoszk236/starred{/owner}{/repo}",
                      "subscriptions_url": "https://api.github.com/users/Bartoszk236/subscriptions",
                      "organizations_url": "https://api.github.com/users/Bartoszk236/orgs",
                      "repos_url": "https://api.github.com/users/Bartoszk236/repos",
                      "events_url": "https://api.github.com/users/Bartoszk236/events{/privacy}",
                      "received_events_url": "https://api.github.com/users/Bartoszk236/received_events",
                      "type": "User",
                      "user_view_type": "public",
                      "site_admin": false
                    },
                    "html_url": "https://github.com/Bartoszk236/codeForces_tasks",
                    "description": null,
                    "fork": false,
                    "url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks",
                    "forks_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/forks",
                    "keys_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/keys{/key_id}",
                    "collaborators_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/collaborators{/collaborator}",
                    "teams_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/teams",
                    "hooks_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/hooks",
                    "issue_events_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/issues/events{/number}",
                    "events_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/events",
                    "assignees_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/assignees{/user}",
                    "branches_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/branches{/branch}",
                    "tags_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/tags",
                    "blobs_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/git/blobs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/git/tags{/sha}",
                    "git_refs_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/git/refs{/sha}",
                    "trees_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/git/trees{/sha}",
                    "statuses_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/statuses/{sha}",
                    "languages_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/languages",
                    "stargazers_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/stargazers",
                    "contributors_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/contributors",
                    "subscribers_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/subscribers",
                    "subscription_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/subscription",
                    "commits_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/commits{/sha}",
                    "git_commits_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/git/commits{/sha}",
                    "comments_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/comments{/number}",
                    "issue_comment_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/issues/comments{/number}",
                    "contents_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/contents/{+path}",
                    "compare_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/compare/{base}...{head}",
                    "merges_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/merges",
                    "archive_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/{archive_format}{/ref}",
                    "downloads_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/downloads",
                    "issues_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/issues{/number}",
                    "pulls_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/pulls{/number}",
                    "milestones_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/milestones{/number}",
                    "notifications_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/notifications{?since,all,participating}",
                    "labels_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/labels{/name}",
                    "releases_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/releases{/id}",
                    "deployments_url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/deployments",
                    "created_at": "2024-11-21T16:37:07Z",
                    "updated_at": "2025-02-05T15:15:52Z",
                    "pushed_at": "2025-03-11T17:21:49Z",
                    "git_url": "git://github.com/Bartoszk236/codeForces_tasks.git",
                    "ssh_url": "git@github.com:Bartoszk236/codeForces_tasks.git",
                    "clone_url": "https://github.com/Bartoszk236/codeForces_tasks.git",
                    "svn_url": "https://github.com/Bartoszk236/codeForces_tasks",
                    "homepage": null,
                    "size": 87,
                    "stargazers_count": 0,
                    "watchers_count": 0,
                    "language": "Java",
                    "has_issues": true,
                    "has_projects": true,
                    "has_downloads": true,
                    "has_wiki": false,
                    "has_pages": false,
                    "has_discussions": false,
                    "forks_count": 0,
                    "mirror_url": null,
                    "archived": false,
                    "disabled": false,
                    "open_issues_count": 0,
                    "license": null,
                    "allow_forking": true,
                    "is_template": false,
                    "web_commit_signoff_required": false,
                    "topics": [],
                    "visibility": "public",
                    "forks": 0,
                    "open_issues": 0,
                    "watchers": 0,
                    "default_branch": "main"
                  },
                  {
                    "id": 1035983157,
                    "node_id": "R_kgDOPb_ZNQ",
                    "name": "github-repos-api",
                    "full_name": "Bartoszk236/github-repos-api",
                    "private": false,
                    "owner": {
                      "login": "Bartoszk236",
                      "id": 148446098,
                      "node_id": "U_kgDOCNkbkg",
                      "avatar_url": "https://avatars.githubusercontent.com/u/148446098?v=4",
                      "gravatar_id": "",
                      "url": "https://api.github.com/users/Bartoszk236",
                      "html_url": "https://github.com/Bartoszk236",
                      "followers_url": "https://api.github.com/users/Bartoszk236/followers",
                      "following_url": "https://api.github.com/users/Bartoszk236/following{/other_user}",
                      "gists_url": "https://api.github.com/users/Bartoszk236/gists{/gist_id}",
                      "starred_url": "https://api.github.com/users/Bartoszk236/starred{/owner}{/repo}",
                      "subscriptions_url": "https://api.github.com/users/Bartoszk236/subscriptions",
                      "organizations_url": "https://api.github.com/users/Bartoszk236/orgs",
                      "repos_url": "https://api.github.com/users/Bartoszk236/repos",
                      "events_url": "https://api.github.com/users/Bartoszk236/events{/privacy}",
                      "received_events_url": "https://api.github.com/users/Bartoszk236/received_events",
                      "type": "User",
                      "user_view_type": "public",
                      "site_admin": false
                    },
                    "html_url": "https://github.com/Bartoszk236/github-repos-api",
                    "description": null,
                    "fork": true,
                    "url": "https://api.github.com/repos/Bartoszk236/github-repos-api",
                    "forks_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/forks",
                    "keys_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/keys{/key_id}",
                    "collaborators_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/collaborators{/collaborator}",
                    "teams_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/teams",
                    "hooks_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/hooks",
                    "issue_events_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/issues/events{/number}",
                    "events_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/events",
                    "assignees_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/assignees{/user}",
                    "branches_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/branches{/branch}",
                    "tags_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/tags",
                    "blobs_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/git/blobs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/git/tags{/sha}",
                    "git_refs_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/git/refs{/sha}",
                    "trees_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/git/trees{/sha}",
                    "statuses_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/statuses/{sha}",
                    "languages_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/languages",
                    "stargazers_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/stargazers",
                    "contributors_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/contributors",
                    "subscribers_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/subscribers",
                    "subscription_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/subscription",
                    "commits_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/commits{/sha}",
                    "git_commits_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/git/commits{/sha}",
                    "comments_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/comments{/number}",
                    "issue_comment_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/issues/comments{/number}",
                    "contents_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/contents/{+path}",
                    "compare_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/compare/{base}...{head}",
                    "merges_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/merges",
                    "archive_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/{archive_format}{/ref}",
                    "downloads_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/downloads",
                    "issues_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/issues{/number}",
                    "pulls_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/pulls{/number}",
                    "milestones_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/milestones{/number}",
                    "notifications_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/notifications{?since,all,participating}",
                    "labels_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/labels{/name}",
                    "releases_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/releases{/id}",
                    "deployments_url": "https://api.github.com/repos/Bartoszk236/github-repos-api/deployments",
                    "created_at": "2025-08-11T11:40:32Z",
                    "updated_at": "2025-08-11T11:40:32Z",
                    "pushed_at": "2025-08-11T11:40:32Z",
                    "git_url": "git://github.com/Bartoszk236/github-repos-api.git",
                    "ssh_url": "git@github.com:Bartoszk236/github-repos-api.git",
                    "clone_url": "https://github.com/Bartoszk236/github-repos-api.git",
                    "svn_url": "https://github.com/Bartoszk236/github-repos-api",
                    "homepage": null,
                    "size": 0,
                    "stargazers_count": 0,
                    "watchers_count": 0,
                    "language": null,
                    "has_issues": true,
                    "has_projects": true,
                    "has_downloads": true,
                    "has_wiki": true,
                    "has_pages": false,
                    "has_discussions": false,
                    "forks_count": 0,
                    "mirror_url": null,
                    "archived": false,
                    "disabled": false,
                    "open_issues_count": 0,
                    "license": null,
                    "allow_forking": true,
                    "is_template": false,
                    "web_commit_signoff_required": false,
                    "topics": [],
                    "visibility": "public",
                    "forks": 0,
                    "open_issues": 0,
                    "watchers": 0,
                    "default_branch": "main"
                  },
                  {
                    "id": 888005465,
                    "node_id": "R_kgDONO3jWQ",
                    "name": "Homework_Mentoring",
                    "full_name": "Bartoszk236/Homework_Mentoring",
                    "private": false,
                    "owner": {
                      "login": "Bartoszk236",
                      "id": 148446098,
                      "node_id": "U_kgDOCNkbkg",
                      "avatar_url": "https://avatars.githubusercontent.com/u/148446098?v=4",
                      "gravatar_id": "",
                      "url": "https://api.github.com/users/Bartoszk236",
                      "html_url": "https://github.com/Bartoszk236",
                      "followers_url": "https://api.github.com/users/Bartoszk236/followers",
                      "following_url": "https://api.github.com/users/Bartoszk236/following{/other_user}",
                      "gists_url": "https://api.github.com/users/Bartoszk236/gists{/gist_id}",
                      "starred_url": "https://api.github.com/users/Bartoszk236/starred{/owner}{/repo}",
                      "subscriptions_url": "https://api.github.com/users/Bartoszk236/subscriptions",
                      "organizations_url": "https://api.github.com/users/Bartoszk236/orgs",
                      "repos_url": "https://api.github.com/users/Bartoszk236/repos",
                      "events_url": "https://api.github.com/users/Bartoszk236/events{/privacy}",
                      "received_events_url": "https://api.github.com/users/Bartoszk236/received_events",
                      "type": "User",
                      "user_view_type": "public",
                      "site_admin": false
                    },
                    "html_url": "https://github.com/Bartoszk236/Homework_Mentoring",
                    "description": null,
                    "fork": false,
                    "url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring",
                    "forks_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/forks",
                    "keys_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/keys{/key_id}",
                    "collaborators_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/collaborators{/collaborator}",
                    "teams_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/teams",
                    "hooks_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/hooks",
                    "issue_events_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/issues/events{/number}",
                    "events_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/events",
                    "assignees_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/assignees{/user}",
                    "branches_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/branches{/branch}",
                    "tags_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/tags",
                    "blobs_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/git/blobs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/git/tags{/sha}",
                    "git_refs_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/git/refs{/sha}",
                    "trees_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/git/trees{/sha}",
                    "statuses_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/statuses/{sha}",
                    "languages_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/languages",
                    "stargazers_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/stargazers",
                    "contributors_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/contributors",
                    "subscribers_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/subscribers",
                    "subscription_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/subscription",
                    "commits_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/commits{/sha}",
                    "git_commits_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/git/commits{/sha}",
                    "comments_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/comments{/number}",
                    "issue_comment_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/issues/comments{/number}",
                    "contents_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/contents/{+path}",
                    "compare_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/compare/{base}...{head}",
                    "merges_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/merges",
                    "archive_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/{archive_format}{/ref}",
                    "downloads_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/downloads",
                    "issues_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/issues{/number}",
                    "pulls_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/pulls{/number}",
                    "milestones_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/milestones{/number}",
                    "notifications_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/notifications{?since,all,participating}",
                    "labels_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/labels{/name}",
                    "releases_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/releases{/id}",
                    "deployments_url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/deployments",
                    "created_at": "2024-11-13T16:45:31Z",
                    "updated_at": "2025-07-23T18:08:50Z",
                    "pushed_at": "2025-08-04T18:30:28Z",
                    "git_url": "git://github.com/Bartoszk236/Homework_Mentoring.git",
                    "ssh_url": "git@github.com:Bartoszk236/Homework_Mentoring.git",
                    "clone_url": "https://github.com/Bartoszk236/Homework_Mentoring.git",
                    "svn_url": "https://github.com/Bartoszk236/Homework_Mentoring",
                    "homepage": null,
                    "size": 344,
                    "stargazers_count": 0,
                    "watchers_count": 0,
                    "language": null,
                    "has_issues": true,
                    "has_projects": true,
                    "has_downloads": true,
                    "has_wiki": false,
                    "has_pages": false,
                    "has_discussions": false,
                    "forks_count": 0,
                    "mirror_url": null,
                    "archived": false,
                    "disabled": false,
                    "open_issues_count": 0,
                    "license": null,
                    "allow_forking": true,
                    "is_template": false,
                    "web_commit_signoff_required": false,
                    "topics": [],
                    "visibility": "public",
                    "forks": 0,
                    "open_issues": 0,
                    "watchers": 0,
                    "default_branch": "main"
                  }
                ]
                """;
    }

    String getBranchesCodeForcesResponseStub() {
        return """
                [
                  {
                    "name": "develop",
                    "commit": {
                      "sha": "1b625ae0e4e4ef7317b33dcbaaa41a121c98dc5d",
                      "url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/commits/1b625ae0e4e4ef7317b33dcbaaa41a121c98dc5d"
                    },
                    "protected": false
                  },
                  {
                    "name": "main",
                    "commit": {
                      "sha": "ec0f76559e0821c14ff9d52bf9694093851498d9",
                      "url": "https://api.github.com/repos/Bartoszk236/codeForces_tasks/commits/ec0f76559e0821c14ff9d52bf9694093851498d9"
                    },
                    "protected": false
                  }
                ]
                """;
    }

    String getBranchesHomeworkResponseStub() {
        return """
                [
                    {
                        "name": "develop",
                        "commit": {
                            "sha": "3e41112d7f8a7998663c5e0c8963a840886035ab",
                            "url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/commits/3e41112d7f8a7998663c5e0c8963a840886035ab"
                        },
                        "protected": false
                    },
                    {
                        "name": "main",
                        "commit": {
                            "sha": "2b3278e0ec0fec284797a2a82c90714a85f34d33",
                            "url": "https://api.github.com/repos/Bartoszk236/Homework_Mentoring/commits/2b3278e0ec0fec284797a2a82c90714a85f34d33"
                        },
                        "protected": false
                    }
                ]
                """;
    }
}
